# Config file. 

[source]
path = "../test_data/source"
filename_mesh = "humerus_sx.key"
filename_landmarks = "landmarks_source.fcsv"
[target]
path = "../test_data/target"
filename_landmarks = "landmarks_target.fcsv"



