# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/infepy',
                'doc_host': 'https://infekit.github.io',
                'git_url': 'https://github.com/infekit/infepy',
                'lib_path': 'infepy'},
  'syms': {'infepy.core': {'infepy.core.foo': ('core.html#foo', 'infepy/core.py')}}}
