# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/infepy',
                'doc_host': 'https://infekit.github.io',
                'git_url': 'https://github.com/infekit/infepy',
                'lib_path': 'infepy'},
  'syms': { 'infepy.morph': {'infepy.morph.morphing': ('1_morphing.html#morphing', 'infepy/morph.py')},
            'infepy.preprocessing': { 'infepy.preprocessing.read_landmarks': ( '0_preprocessing.html#read_landmarks',
                                                                               'infepy/preprocessing.py'),
                                      'infepy.preprocessing.read_nodes': ('0_preprocessing.html#read_nodes', 'infepy/preprocessing.py')}}}
