# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/infepy',
                'doc_host': 'https://infekit.github.io',
                'git_url': 'https://github.com/infekit/infepy',
                'lib_path': 'infepy'},
  'syms': { 'infepy.module_test': {'infepy.module_test._test_landmarks': ('test.html#_test_landmarks', 'infepy/module_test.py')},
            'infepy.morph': {'infepy.morph.morphing': ('1_morphing.html#morphing', 'infepy/morph.py')},
            'infepy.preprocessing': { 'infepy.preprocessing._check_landmarks': ( '0_preprocessing.html#_check_landmarks',
                                                                                 'infepy/preprocessing.py'),
                                      'infepy.preprocessing.read_landmarks': ( '0_preprocessing.html#read_landmarks',
                                                                               'infepy/preprocessing.py'),
                                      'infepy.preprocessing.read_nodes': ('0_preprocessing.html#read_nodes', 'infepy/preprocessing.py')},
            'infepy.utils': { 'infepy.utils._merge_path': ('2_utils.html#_merge_path', 'infepy/utils.py'),
                              'infepy.utils.multiple_targets': ('2_utils.html#multiple_targets', 'infepy/utils.py'),
                              'infepy.utils.read_toml': ('2_utils.html#read_toml', 'infepy/utils.py')}}}
