# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/9_demo_jupyter.ipynb.

# %% auto 0
__all__ = ['source_landmarks_file', 'target_landmarks_file', 'source_mesh_file', 'destination_file', 'source_landmarks',
           'target_landmarks', 'source_mesh', 'morphed_mesh']

# %% ../nbs/9_demo_jupyter.ipynb 4
from .morph import morphing
from .preprocessing import read_landmarks, read_nodes, write_output

# %% ../nbs/9_demo_jupyter.ipynb 7
# |eval: false
source_landmarks_file = "../test_data/source/landmarks_source.fcsv"
target_landmarks_file = "../test_data/target/100014/landmarks_target.csv"
source_mesh_file = "../test_data/humerus_sx.key"
destination_file = "../test_data/target/100014/humerus_morphed.key"

# %% ../nbs/9_demo_jupyter.ipynb 10
# |eval: false
source_landmarks = read_landmarks(source_landmarks_file)
target_landmarks = read_landmarks(target_landmarks_file)
source_mesh = read_nodes(source_mesh_file)

# %% ../nbs/9_demo_jupyter.ipynb 12
# |eval: false
morphed_mesh = morphing(
    source_landmarks,
    target_landmarks,
    source_mesh,
    func="thin_plate_spline",
    smoothing=0,
)

# %% ../nbs/9_demo_jupyter.ipynb 14
# |eval: false
write_output(morphed_mesh, destination_file, source_mesh_file)
