# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/0_preprocessing.ipynb.

# %% auto 0
__all__ = ['read_nodes', 'read_landmarks']

# %% ../nbs/0_preprocessing.ipynb 3
def read_nodes():
    "Read the nodes from the source template"
    pass

# %% ../nbs/0_preprocessing.ipynb 4
def read_landmarks():
    "Read the landmarks from file. "
    pass
