# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/2_utils.ipynb.

# %% auto 0
__all__ = ['read_toml', 'merge_path']

# %% ../nbs/2_utils.ipynb 3
import os
import toml

# %% ../nbs/2_utils.ipynb 4
def read_toml(  config_file= "Config.toml" # Path to the config file
):
    "Read setting file. The File containes the relative path to source and target."
    config= toml.load(config_file)
    return config
    

# %% ../nbs/2_utils.ipynb 6
def merge_path( path1, path2) :
    "Join one or more path components. Return the join path in str type."
    return os.path.join(path1,path2)
