# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/2_utils.ipynb.

# %% auto 0
__all__ = ['read_toml', 'multiple_targets']

# %% ../nbs/2_utils.ipynb 3
import os
import toml

# %% ../nbs/2_utils.ipynb 4
def read_toml(  config_file= "Config.toml" # Path to the config file
):
    "Read setting file. The File containes the relative path to source and target."
    config= toml.load(config_file)
    return config
    

# %% ../nbs/2_utils.ipynb 6
def _merge_path(path1:str , path2: str)-> str:
    "Join one or more path components. Return the join path in str type."
    return os.path.join(path1,path2)

# %% ../nbs/2_utils.ipynb 8
def multiple_targets():
    "This function checks if the there are multiple target subject."
    config = read_toml()
    path= config['target']['path']
    filename = config['target']['filename_landmarks']
    list_target= [name for name in os.listdir(path) if os.path.isdir(os.path.join(path, name))]
    if not list_target:
        assert os.path.isfile(_merge_path(path, filename)), "No file with Landmarks"
        return False
    else:
        return list_target

