name: Deploy to GitHub Pages
on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Pygem
        run: pip install git+https://github.com/mathLab/PyGeM

      - name: Quarto
        uses: fastai/workflows/quarto-ghp@master
