name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy_id:
    runs-on: ubuntu-latest
    steps: [ uses: fastai/workflows/quarto-ghp@master]
    - name: Upgrade pip
      run: python -m pip install --upgrade 
    
    - name: Install Pygem
      run: pip git+https://github.com/mathLab/PyGeM

