name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: [ uses: fastai/workflows/quarto-ghp@master]
      # - name: Install Pygem
      #   run: python -m pip install --upgrade pip git+https://github.com/mathLab/PyGeM
    