name: Deploy to GitHub Pages
on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:
jobs:
  deploy_id:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade pip
        uses: fastai/workflows/quarto-ghp@master
        run: python -m pip install --upgrade

      - name: Install Pygem
        uses: fastai/workflows/quarto-ghp@master
        run: pip git+https://github.com/mathLab/PyGeM
